DROP TABLE IF EXISTS example_4.transactions;
DROP SCHEMA IF EXISTS example_4;
CREATE SCHEMA example_4;

CREATE TABLE example_4.transactions (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	organization_id int NULL,
	CONSTRAINT pk_transactions PRIMARY KEY (id)
);
 
INSERT INTO example_4.transactions (organization_id)
SELECT ROUND((random() * 100 + 1)::numeric)
FROM generate_series(1, 1000000, 1) AS id;

-- Answer
-- Create materialized view for distinct organization_ids
CREATE MATERIALIZED VIEW example_4.distinct_organization_ids AS
SELECT organization_id
FROM example_4.transactions
GROUP BY organization_id

--  Query the materialized view to get distinct organization ids
SELECT * FROM example_4.distinct_organization_ids;
